version: "3"

services:
  app:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    restart: always
  db:
    image: vimagick/json-server
    container_name: json-server
    command: --watch /data/db/db.json -H 0.0.0.0 -p 3333 --delay 700
    ports:
      - 3333:3333
    volumes:
      - ./src/services/db:/data/db
    restart: always